In [1]:
%matplotlib inline

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from datetime import datetime

In [29]:
part1_result = pd.read_csv('part1.csv')
part2_result = pd.read_csv('part2.csv')
part3_result = pd.read_csv('part3.csv')
part4_result = pd.read_csv('part4.csv')

In [31]:
part1_result.head()

   row_id                           place_id
0       0   7652380351 3831655216 6253981821
1       3   7995458948 3243409743 8393706174
2       5   8370753254 9727638738 8556108428
3      14   3756584599 7405695170 7802057913
4      15   4390687315 2437541306 8442351461

In [33]:
final_result = pd.concat([part1_result, part2_result, part3_result, part4_result])

In [38]:
final_result_sorted = final_result.sort_values(['row_id'])z

In [39]:
final_result_sorted

          row_id                           place_id
0              0   7652380351 3831655216 6253981821
0              1   9801651394 5801740503 2465239230
1              2   7862615088 2516481553 2653128693
1              3   7995458948 3243409743 8393706174
0              4   4764406629 8277155346 8711861736
2              5   8370753254 9727638738 8556108428
2              6   7283245557 3165318731 7564010400
3              7   2482334547 2247481267 4346049470
1              8   6421756522 6470278079 1496969742
2              9   3894834079 6980929490 2028638270
3             10   1776286518 8209128517 3641802545
4             11   5011847413 6955556885 4785518658
5             12   9031150064 4000363114 6291666280
4             13   5313553144 2434531540 3420992015
3             14   3756584599 7405695170 7802057913
4             15   4390687315 2437541306 8442351461
5             16   8015849918 6368539484 9440230828
6             17   6318300870 8792019238 3221204410
6             18   2865997311 4545725062 3725878383
5             19   8151914846 1774249595 1692842864
6             20   5937599993 7247882702 4978915536
0             21   6990989086 4289747407 4421934994
7             22   7840467506 4867295788 5708581121
7             23   1422868699 9579277377 5045456877
7             24   9366346488 3221366284 6540157418
8             25   7563100425 9292390996 7045025665
8             26   5861390859 9152743506 4911383584
8             27   2488350841 8977862655 7219316142
1             28   4070072518 9009546926 5673067398
9             29   7774874828 7441010909 6952731752
...          ...                                ...
2137692  8607200   7010348345 8679720585 2943292665
2147375  8607201   4629681069 1355744013 9832223498
2166653  8607202   5419947686 1087968716 3379648998
2147376  8607203   8018708440 3104040452 1580699401
2147377  8607204   2347597778 5735882732 5911617733
2166654  8607205   5625458185 7842891429 5042215560
2155308  8607206   4502177541 2805665832 9320057374
2147378  8607207   2004263384 2765466042 1350115615
2147379  8607208   9200050341 7598550430 3777667176
2137693  8607209   7152166798 3327253913 3735402844
2155309  8607210   6983746532 6149892852 6094880639
2147380  8607211   3462978534 3759912905 5451164453
2147381  8607212   5599832779 3459932335 5541777288
2155310  8607213   3979869807 5556517315 5668453139
2155311  8607214   3465077813 9733096030 8398982147
2137694  8607215   2393010185 6810867359 6025435190
2155312  8607216   4314460660 3123784059 5800871217
2137695  8607217   7295234444 5052683076 1685632544
2166655  8607218   5435941405 7815053482 6653133495
2155313  8607219   8364800794 6906835688 4920677861
2155314  8607220   9924871949 3278278289 7656187423
2166656  8607221   8933542378 5378587809 8792295459
2147382  8607222   4683526794 2813163259 7429659042
2137696  8607223   2614601100 4642612962 9244044921
2147383  8607224   7519528207 7053690910 7336608920
2166657  8607225   6388207576 5831495752 1450752225
2137697  8607226   9482625693 8203932359 6379437992
2137698  8607227   9466512367 3362837051 2817562084
2155315  8607228   6645978051 8822589364 2649611830
2137699  8607229   1221929656 2341683842 9400117788

[8607058 rows x 2 columns]

In [42]:
final_result_sorted.index = np.arange(0,8607058)

In [43]:
final_result_sorted

          row_id                           place_id
0              0   7652380351 3831655216 6253981821
1              1   9801651394 5801740503 2465239230
2              2   7862615088 2516481553 2653128693
3              3   7995458948 3243409743 8393706174
4              4   4764406629 8277155346 8711861736
5              5   8370753254 9727638738 8556108428
6              6   7283245557 3165318731 7564010400
7              7   2482334547 2247481267 4346049470
8              8   6421756522 6470278079 1496969742
9              9   3894834079 6980929490 2028638270
10            10   1776286518 8209128517 3641802545
11            11   5011847413 6955556885 4785518658
12            12   9031150064 4000363114 6291666280
13            13   5313553144 2434531540 3420992015
14            14   3756584599 7405695170 7802057913
15            15   4390687315 2437541306 8442351461
16            16   8015849918 6368539484 9440230828
17            17   6318300870 8792019238 3221204410
18            18   2865997311 4545725062 3725878383
19            19   8151914846 1774249595 1692842864
20            20   5937599993 7247882702 4978915536
21            21   6990989086 4289747407 4421934994
22            22   7840467506 4867295788 5708581121
23            23   1422868699 9579277377 5045456877
24            24   9366346488 3221366284 6540157418
25            25   7563100425 9292390996 7045025665
26            26   5861390859 9152743506 4911383584
27            27   2488350841 8977862655 7219316142
28            28   4070072518 9009546926 5673067398
29            29   7774874828 7441010909 6952731752
...          ...                                ...
8607028  8607200   7010348345 8679720585 2943292665
8607029  8607201   4629681069 1355744013 9832223498
8607030  8607202   5419947686 1087968716 3379648998
8607031  8607203   8018708440 3104040452 1580699401
8607032  8607204   2347597778 5735882732 5911617733
8607033  8607205   5625458185 7842891429 5042215560
8607034  8607206   4502177541 2805665832 9320057374
8607035  8607207   2004263384 2765466042 1350115615
8607036  8607208   9200050341 7598550430 3777667176
8607037  8607209   7152166798 3327253913 3735402844
8607038  8607210   6983746532 6149892852 6094880639
8607039  8607211   3462978534 3759912905 5451164453
8607040  8607212   5599832779 3459932335 5541777288
8607041  8607213   3979869807 5556517315 5668453139
8607042  8607214   3465077813 9733096030 8398982147
8607043  8607215   2393010185 6810867359 6025435190
8607044  8607216   4314460660 3123784059 5800871217
8607045  8607217   7295234444 5052683076 1685632544
8607046  8607218   5435941405 7815053482 6653133495
8607047  8607219   8364800794 6906835688 4920677861
8607048  8607220   9924871949 3278278289 7656187423
8607049  8607221   8933542378 5378587809 8792295459
8607050  8607222   4683526794 2813163259 7429659042
8607051  8607223   2614601100 4642612962 9244044921
8607052  8607224   7519528207 7053690910 7336608920
8607053  8607225   6388207576 5831495752 1450752225
8607054  8607226   9482625693 8203932359 6379437992
8607055  8607227   9466512367 3362837051 2817562084
8607056  8607228   6645978051 8822589364 2649611830
8607057  8607229   1221929656 2341683842 9400117788

[8607058 rows x 2 columns]

In [50]:
final_result_sorted.to_csv('total.csv')